-- Title: D3 Basketball Database
-- Authors: Aidan Von Buchwaldt, Basil Shevtsov, and Jai Deshpande

INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6977, 2, 'Luis', 'Garcia', 'Center', 69, 225, 'Rios, Harvey and Rosales');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2491, 83, 'Kyle', 'Adams', 'Guard', 84, 210, 'Butler, Page and Miles');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4622, 58, 'Joel', 'Rios', 'Center', 85, 218, 'Jones, Taylor and Camacho');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5935, 40, 'Jason', 'Martin', 'Guard', 84, 198, 'Vaughn PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7583, 92, 'Nicole', 'Watts', 'Forward', 72, 178, 'Logan Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7039, 61, 'Tiffany', 'Rodriguez', 'Guard', 77, 182, 'Carrillo, Simmons and Lewis');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9303, 55, 'Joshua', 'Gray', 'Guard', 65, 164, 'Nash-Hunter');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3447, 58, 'Nathan', 'Dixon', 'Forward', 79, 179, 'Carpenter-Chaney');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8380, 71, 'Michael', 'Daugherty', 'Forward', 80, 242, 'Soto Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7340, 36, 'Sarah', 'Booker', 'Guard', 67, 204, 'Salinas PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4108, 36, 'Nicole', 'Hebert', 'Forward', 69, 160, 'Roberts LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4153, 62, 'Kenneth', 'Duffy', 'Center', 74, 211, 'Gray Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5012, 64, 'Sarah', 'Smith', 'Guard', 85, 244, 'Williams Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6157, 73, 'George', 'Sharp', 'Center', 66, 207, 'Hancock, Horn and Jones');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1729, 51, 'Lisa', 'Nguyen', 'Guard', 73, 208, 'Maynard, Hale and Coleman');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9506, 29, 'Vanessa', 'Carson', 'Guard', 82, 239, 'Whitaker-Robinson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (769, 97, 'Jamie', 'Gilmore', 'Center', 82, 179, 'Willis-Horton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7268, 100, 'Jeffrey', 'Watson', 'Forward', 73, 152, 'Benson-Blevins');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (726, 24, 'Taylor', 'Copeland', 'Guard', 74, 211, 'Williams-Terry');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7337, 37, 'Scott', 'Bell', 'Guard', 85, 191, 'Banks-Contreras');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7643, 13, 'Brenda', 'Mccarty', 'Forward', 83, 194, 'Campbell, Armstrong and Jackson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7006, 11, 'Andre', 'Anderson', 'Guard', 71, 165, 'Andrews-Lopez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5905, 35, 'Scott', 'Burke', 'Guard', 81, 164, 'Rose-Atkinson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (15, 61, 'Carolyn', 'Edwards', 'Center', 79, 191, 'Baker-Brown');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2997, 29, 'Scott', 'Murphy', 'Guard', 66, 154, 'Atkins, Harrell and Mullins');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6537, 85, 'Katherine', 'Thompson', 'Guard', 80, 205, 'Obrien-Savage');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (958, 8, 'Debbie', 'Chapman', 'Center', 81, 243, 'Whitney, Hall and Taylor');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1946, 60, 'Omar', 'Torres', 'Forward', 77, 194, 'Santos PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (992, 16, 'Samantha', 'Chen', 'Center', 65, 170, 'Pierce, Zavala and West');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9272, 46, 'Jennifer', 'Gomez', 'Center', 76, 247, 'Kim-Burton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6245, 47, 'Gerald', 'Rios', 'Guard', 84, 150, 'Hogan Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7062, 86, 'Jeremiah', 'Hoffman', 'Guard', 84, 241, 'King-Wilson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2316, 9, 'Manuel', 'Ward', 'Guard', 68, 194, 'Martin, Tyler and Davis');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5668, 83, 'Meghan', 'Walter', 'Center', 66, 221, 'Wilson, Cruz and Sanchez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5673, 14, 'Ashley', 'Johnson', 'Forward', 66, 222, 'Meza, Nunez and Hogan');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2956, 36, 'James', 'Williams', 'Guard', 65, 216, 'Garcia, Reid and Gonzalez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7838, 93, 'Larry', 'Davenport', 'Center', 72, 189, 'Medina, Cook and Stewart');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1454, 19, 'Sarah', 'Roberts', 'Guard', 66, 175, 'Lewis, Campbell and Baker');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3816, 31, 'Lori', 'Weaver', 'Guard', 69, 194, 'Jones, Escobar and Johnson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6851, 59, 'Michelle', 'Riggs', 'Forward', 72, 155, 'Poole, Morris and Watson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7533, 75, 'Joshua', 'Walton', 'Guard', 70, 163, 'Miller, Miller and Montgomery');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1310, 93, 'Jesse', 'Wilson', 'Guard', 78, 200, 'Yang, Lewis and Williams');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9229, 83, 'Olivia', 'Gray', 'Center', 84, 234, 'Brewer-White');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7862, 45, 'Stephanie', 'Manning', 'Forward', 78, 196, 'Cortez LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8514, 32, 'Michael', 'Bond', 'Center', 77, 176, 'White PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (272, 2, 'Robert', 'Brown', 'Guard', 71, 247, 'Zimmerman Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8711, 70, 'Maria', 'Carlson', 'Guard', 76, 167, 'Mcclain, Moore and Campbell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4413, 30, 'Daniel', 'Schultz', 'Guard', 83, 229, 'Glenn, Brooks and Brown');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2626, 36, 'Miranda', 'Williamson', 'Guard', 82, 199, 'Sweeney, Little and Dennis');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7428, 3, 'Ronnie', 'Stout', 'Guard', 73, 182, 'Flores-Benson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8910, 86, 'Michelle', 'Rodriguez', 'Guard', 69, 196, 'Miller PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5809, 45, 'Maurice', 'Paul', 'Guard', 66, 232, 'Brooks Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4812, 64, 'Christine', 'Smith', 'Guard', 65, 175, 'Johnson-Murphy');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (731, 7, 'Lori', 'Giles', 'Center', 84, 250, 'Newman-Paul');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9178, 2, 'Lori', 'Dodson', 'Forward', 83, 206, 'Cherry Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6624, 17, 'Alisha', 'Palmer', 'Forward', 75, 211, 'Mcbride-Morgan');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5194, 75, 'Lauren', 'Carter', 'Forward', 67, 244, 'Garcia-Blake');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5278, 94, 'Sydney', 'Johnson', 'Guard', 76, 246, 'Baker, Fields and Rodriguez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1350, 17, 'Ian', 'Garcia', 'Forward', 66, 164, 'Davidson, Walters and Hutchinson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7056, 72, 'Timothy', 'Townsend', 'Forward', 80, 153, 'Mcclure, Williams and Roberts');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7235, 50, 'Michael', 'Doyle', 'Center', 67, 209, 'Maxwell-Thomas');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3859, 91, 'Julia', 'Ortiz', 'Center', 71, 174, 'Lewis, Murray and Jordan');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7825, 48, 'David', 'Carter', 'Center', 77, 173, 'Hernandez and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9898, 49, 'William', 'Jackson', 'Forward', 65, 234, 'Rodriguez-Chapman');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1410, 75, 'Heather', 'Bryant', 'Guard', 74, 246, 'Rose-Tucker');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8582, 8, 'Richard', 'Parsons', 'Guard', 76, 223, 'Smith Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4051, 55, 'Stephanie', 'Rodriguez', 'Forward', 68, 167, 'Graham-Nichols');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2361, 60, 'Dawn', 'Morris', 'Forward', 70, 217, 'Garcia, Townsend and Horton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7997, 66, 'Emily', 'Spencer', 'Forward', 66, 199, 'Blair-Olson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2825, 12, 'Crystal', 'Harrison', 'Guard', 80, 233, 'Francis-Lowe');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1175, 12, 'Joshua', 'Diaz', 'Forward', 82, 207, 'Smith Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4253, 67, 'Laura', 'Sparks', 'Center', 67, 201, 'Mendoza-Mitchell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4284, 8, 'Patrick', 'Mitchell', 'Center', 76, 235, 'Smith, Adams and Aguirre');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8120, 38, 'Jonathan', 'Murray', 'Center', 85, 243, 'Stevens-Johnson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6392, 63, 'Beth', 'Carlson', 'Forward', 82, 170, 'Paul-Hodge');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4189, 49, 'Ian', 'Lane', 'Forward', 68, 237, 'Campbell-Wright');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5335, 28, 'Elaine', 'Velazquez', 'Forward', 82, 155, 'Bray-Rodriguez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1967, 94, 'Gregory', 'Norris', 'Center', 71, 201, 'Armstrong-Moore');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3324, 5, 'Allison', 'Miller', 'Guard', 76, 166, 'Edwards, Dixon and Smith');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5185, 98, 'Caroline', 'Sparks', 'Forward', 65, 244, 'Sanchez Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1868, 8, 'Amy', 'Castaneda', 'Guard', 67, 151, 'Cuevas, Fowler and Wright');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4990, 67, 'Elizabeth', 'Wilson', 'Center', 67, 213, 'Smith, Lopez and Butler');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6540, 23, 'William', 'Stevenson', 'Guard', 81, 235, 'Mcdaniel, Mckinney and Stanton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8553, 67, 'Amy', 'Livingston', 'Forward', 79, 152, 'Garza-Torres');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2022, 72, 'Jeffrey', 'Ramos', 'Center', 75, 248, 'Krueger Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5162, 12, 'Dana', 'Palmer', 'Center', 78, 215, 'Anthony-Webb');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4065, 11, 'Raymond', 'Richards', 'Forward', 79, 232, 'Jones Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5864, 15, 'Jason', 'Reyes', 'Guard', 79, 161, 'Perez, Ortega and Spears');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8408, 62, 'Tammy', 'Petty', 'Center', 75, 188, 'Walsh, Nicholson and Rodriguez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (597, 58, 'Kimberly', 'Barton', 'Forward', 69, 237, 'Mckinney, Hansen and Hill');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2286, 5, 'Catherine', 'Wallace', 'Guard', 67, 180, 'Allen-Murphy');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6665, 50, 'Barbara', 'Lozano', 'Guard', 66, 201, 'Singh-Foley');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1318, 82, 'Robert', 'Lynn', 'Forward', 80, 228, 'Adams-Meyer');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9871, 88, 'Stacy', 'Howe', 'Center', 85, 177, 'Miller PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5799, 31, 'Chris', 'Rios', 'Guard', 79, 183, 'Olson and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4081, 82, 'Kevin', 'Bond', 'Center', 85, 196, 'Copeland-Brown');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2297, 31, 'David', 'Spears', 'Center', 67, 174, 'Martinez-Edwards');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7186, 100, 'Katherine', 'Richardson', 'Guard', 71, 158, 'Parks, Ochoa and Mason');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5836, 24, 'Edward', 'Burton', 'Forward', 72, 165, 'Alvarado, Watkins and Jackson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1548, 55, 'Cynthia', 'Molina', 'Forward', 80, 177, 'Compton, Adams and King');
