INSERT INTO Team (TeamID, TeamName, Location) VALUES (470, 'Martin-Murray', 'Margaretborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (477, 'Walker-Gomez', 'West Codyhaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (277, 'Gomez, Keller and Green', 'East Mary');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (222, 'Mathis-Davis', 'North Stephanie');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (165, 'Johnson, Contreras and Walters', 'South Michaelchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (735, 'Taylor-Wright', 'West Lisa');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (640, 'Brown, Henderson and Harrington', 'Schultzshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (427, 'Riley-Curry', 'East Jeffshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (313, 'Robertson LLC', 'Petersonfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (973, 'Roberts, Carlson and Lloyd', 'Stewartside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (484, 'Turner, Parker and Hanson', 'New Steventown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (155, 'Gonzalez PLC', 'Millerland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (654, 'Martinez Ltd', 'Kennethshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (204, 'Wiggins Ltd', 'Ericland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (876, 'Watts-Thomas', 'Clarktown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (544, 'Frye-Day', 'North Travis');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (211, 'Hanna-Gonzalez', 'West Brandi');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (318, 'Thomas, Williams and Bailey', 'New Frederick');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (605, 'Jackson Group', 'Williamsonchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (391, 'Chapman-Martinez', 'New Meganbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (727, 'Clark-Blackwell', 'Lake Stevenfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (366, 'Smith-Wagner', 'Johnnyville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (128, 'Brown, Collins and Rosales', 'Brownhaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (395, 'Farmer-Lane', 'West Charles');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (284, 'Bell-Rich', 'Maychester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (548, 'James-Andrews', 'South Edwin');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (114, 'Frazier Group', 'South Denise');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (564, 'Foster PLC', 'New Calvinville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (741, 'Harris, Nelson and Saunders', 'Guerrerohaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (800, 'West and Sons', 'Stephanieland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (346, 'Smith and Sons', 'Maystown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (133, 'Parks, Patrick and Morris', 'South Roymouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (72, 'Villarreal Ltd', 'South Amy');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (23, 'Lang, Houston and Stevens', 'Lonniemouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (719, 'Warren Group', 'Braunbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (83, 'Walker, Walker and Ingram', 'New Valerieshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (494, 'Marshall PLC', 'Humphreytown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (375, 'Brooks Ltd', 'Port Spencerview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (608, 'Johnson Group', 'New Carla');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (79, 'Carter LLC', 'Johnsonview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (635, 'Roberts LLC', 'Sullivanside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (555, 'Davis-Perez', 'South Tanyaland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (564, 'Coleman, Callahan and Phelps', 'Frostburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (444, 'Lee, Jennings and Mcgee', 'South John');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (972, 'Adkins, Greene and Levy', 'Johnview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (697, 'Pierce Inc', 'Peterberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (413, 'Vance Group', 'New Destiny');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (292, 'Houston, Abbott and Martinez', 'Deborahside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (74, 'Pugh, Ross and Knight', 'Lake Angelaberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (652, 'Stone-Phelps', 'Jeremyville');
