-- Title: D3 Basketball Database
-- Authors: Aidan Von Buchwaldt, Basil Shevtsov, and Jai Deshpande

INSERT INTO Team (TeamID, TeamName, Location) VALUES (424, 'Phillips, Lee and Carter', 'Port Linda');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (721, 'Hensley, Edwards and Donovan', 'New Stephaniefort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (554, 'Arroyo-Stark', 'East Ryanbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (274, 'Leonard-Jones', 'Lake Jerry');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (422, 'Fowler, Sanders and Brown', 'Bushberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (55, 'Hunt Ltd', 'West John');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (313, 'Thomas LLC', 'Davidburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (749, 'Cooper-Morris', 'South Sydneyview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (834, 'Brown-Baker', 'Sarahton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (845, 'Parker, Jones and Tucker', 'South Thomas');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (574, 'Hill Group', 'North Derrick');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (655, 'Torres-Mcclure', 'Jaymouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (251, 'Rubio, Benson and Rodriguez', 'Dianestad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (581, 'Robertson Group', 'Deniseland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (34, 'Wagner LLC', 'New Amber');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (966, 'Holland, Olson and Holland', 'Bartlettborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (297, 'Vargas-Johnson', 'New Daniel');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (657, 'Barber Inc', 'Lake Michael');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (868, 'Chang, Garcia and Rogers', 'Brookestad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (316, 'Holland LLC', 'North Jaredton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (149, 'Brown, Harrell and Beasley', 'Jasonville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (305, 'Gutierrez, Robinson and King', 'East Nicholaston');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (450, 'Walker, Gross and Garcia', 'Lake Sydneyshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (615, 'Brown, Bradley and Pham', 'Amandaton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (259, 'Montes-Kelly', 'Townsendchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (570, 'Thompson, Reed and Schultz', 'North Deborah');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (718, 'Munoz-Allen', 'Zavalabury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (77, 'Miles, Williams and Gray', 'North Patricia');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (410, 'West-Stewart', 'South Terri');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (723, 'Velez Ltd', 'Port Shannon');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (655, 'Johnson PLC', 'Smithhaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (969, 'Parrish, Pennington and Brooks', 'Andersonmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (248, 'Berry Group', 'North Teresa');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (794, 'Kim-Morris', 'Josephbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (337, 'Murray-Lam', 'Shepherdchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (221, 'Crawford-Tucker', 'Shawport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (276, 'Sweeney and Sons', 'New Jamietown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (849, 'Blevins, Weber and Lopez', 'Port Ericton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (915, 'House, Wade and Martin', 'North Tracy');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (673, 'Roy-Howe', 'Port Loriville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (363, 'Robbins-Dennis', 'East Maryville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (107, 'Mercado Group', 'Samanthahaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (945, 'Alexander PLC', 'Lake Nicholas');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (598, 'Baker PLC', 'Jordanview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (128, 'Price Ltd', 'New Aaronside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (619, 'Hardin, Henry and Williams', 'East Kristin');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (227, 'Wilson LLC', 'Kyleport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (35, 'Chung-Miller', 'Lozanoberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (36, 'Matthews-Manning', 'Mistystad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (714, 'Noble, Perry and Marshall', 'Danielburgh');
