INSERT INTO Team (TeamID, TeamName, Location) VALUES (96, 'Foster, Lane and Anderson', 'Jenniferside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (5, 'Baldwin, Russell and Collins', 'Lake Sarah');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (43, 'Ryan, Clark and Nguyen', 'Port Christophermouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (68, 'Stokes, Pham and Thomas', 'Williamchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (43, 'Turner-Graham', 'Lake Shellymouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (15, 'Johnson Group', 'Suttonton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (91, 'Barr-Burgess', 'New Miguel');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (71, 'Fuller-Porter', 'Port Paula');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (38, 'Jones, Johnson and Hamilton', 'Perkinschester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (50, 'Cruz-Brown', 'Port Sarahshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (13, 'Cooper LLC', 'West Joseph');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (28, 'Perry, James and Bowman', 'Lake Aprilburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (21, 'Barron-Ibarra', 'Andrewside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (70, 'Russo-Parker', 'Richview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (41, 'Johnson Ltd', 'Gutierrezchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (29, 'Ross Inc', 'Angelafort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (90, 'Thompson Group', 'West Denise');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (32, 'Santos LLC', 'Michaelton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (68, 'Contreras and Sons', 'Lake Karen');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (41, 'Ramirez-Franklin', 'Leport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (8, 'Brown-Rodriguez', 'Harveyton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (99, 'Simmons and Sons', 'Mollyshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (10, 'Padilla, Davis and Medina', 'Jeffreyfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (1, 'Mccoy Ltd', 'Miguelborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (58, 'Sanchez, Dean and Brennan', 'Vanessafort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (1, 'Anderson-Wiggins', 'Simpsonmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (3, 'Miller, Jensen and Norris', 'South Justin');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (59, 'Mclean Group', 'North Jennifer');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (82, 'Frank-Johnson', 'Jenniferchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (38, 'Gonzalez LLC', 'Alexanderton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (79, 'White Inc', 'Justinchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (28, 'Hall Inc', 'Port Nataliestad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (95, 'Sheppard-Price', 'Spencerton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (53, 'White-Rodriguez', 'Howardchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (13, 'Harris, Bartlett and Morales', 'North David');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (58, 'Robinson PLC', 'Lake Margaretville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (63, 'Gray-Cameron', 'East Jennifer');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (54, 'Lopez, Phillips and Petersen', 'Lake Derrickbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (38, 'Hartman-Scott', 'Adamsside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (24, 'Gonzalez and Sons', 'Lake Todd');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (57, 'Ryan-Johnson', 'North Kenneth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (37, 'Kirby, Tucker and Baker', 'New Jamieburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (82, 'Peterson, Cox and Gibson', 'Lake Peter');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (42, 'Collins-Alexander', 'Kaiserside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (33, 'Collier, Duffy and Mckinney', 'Stevensborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (92, 'Bishop, Palmer and Martinez', 'Ericastad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (63, 'Williams-Gibson', 'South Davidport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (24, 'Gonzalez-Ramirez', 'Bradleyfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (11, 'Juarez, Page and Gallagher', 'Williamchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (22, 'Romero Ltd', 'Lake Dennis');
