-- Title: D3 Basketball Database
-- File: Project Data for Players Table
-- Authors: Aidan Von Buchwaldt, Basil Shevtsov, and Jai Deshpande
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3799, 3, 'Brandon', 'Medina', 'Guard', 84, 177, 'Martinez, Mccoy and Jones');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2409, 10, 'David', 'Lamb', 'Center', 66, 249, 'Thomas, Lewis and Adams');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3210, 21, 'Andrew', 'Mason', 'Guard', 82, 185, 'Chavez-Owens');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5507, 24, 'Shawn', 'Burton', 'Center', 79, 241, 'Gross Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4060, 20, 'Jacob', 'Olson', 'Forward', 66, 233, 'Curtis PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3116, 12, 'Lori', 'Wise', 'Forward', 79, 160, 'Beasley and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4852, 2, 'Stanley', 'Graham', 'Guard', 84, 155, 'Parsons, Smith and Thompson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1939, 22, 'Sara', 'Cole', 'Forward', 77, 239, 'Mendoza-Parker');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (964, 6, 'Heather', 'Evans', 'Guard', 67, 197, 'Jones, Parker and Jones');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (118, 5, 'Pamela', 'Lynn', 'Guard', 69, 183, 'Barnes, Brooks and Stevenson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8867, 8, 'Eric', 'Williams', 'Guard', 76, 220, 'Richardson Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9990, 15, 'Renee', 'Ryan', 'Forward', 78, 248, 'Pineda-Ford');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9237, 1, 'Edwin', 'White', 'Forward', 65, 159, 'Harris, Smith and Jordan');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3498, 10, 'Alexander', 'Clark', 'Forward', 65, 164, 'Shaffer and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1341, 13, 'Shane', 'Schwartz', 'Forward', 82, 235, 'Richardson, Moore and Campbell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4064, 7, 'Robert', 'Gordon', 'Forward', 77, 213, 'Le, Kramer and Richardson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6616, 6, 'Mary', 'Parks', 'Forward', 74, 190, 'Jacobs LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3539, 6, 'Kylie', 'Smith', 'Center', 83, 161, 'Norris-Bean');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7792, 17, 'Ryan', 'Jones', 'Forward', 80, 168, 'Williams Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9304, 17, 'Karen', 'Williams', 'Center', 82, 248, 'Hall Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8473, 8, 'Benjamin', 'Vaughn', 'Guard', 83, 191, 'Christensen PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1088, 1, 'Peggy', 'Cobb', 'Guard', 71, 170, 'Mercado, Price and Smith');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (919, 2, 'Michael', 'Gonzalez', 'Center', 83, 203, 'Stevens, Rogers and Richardson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1630, 4, 'Douglas', 'Stewart', 'Forward', 83, 159, 'Johnson PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3731, 12, 'Jessica', 'Burgess', 'Center', 71, 172, 'Torres, Dominguez and Harris');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5159, 8, 'Haley', 'Romero', 'Guard', 68, 218, 'Hooper, Hicks and Andrews');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8386, 7, 'Patty', 'Ferguson', 'Guard', 65, 209, 'Williams-Murray');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4054, 8, 'Timothy', 'Hanson', 'Center', 81, 191, 'Wallace Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7188, 6, 'Diane', 'Henderson', 'Forward', 68, 239, 'Jenkins LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6552, 20, 'John', 'Hess', 'Center', 78, 155, 'Smith-Mcgee');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9918, 19, 'Sara', 'Walter', 'Forward', 74, 228, 'Gonzalez, Moses and Pugh');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5704, 1, 'James', 'Peterson', 'Guard', 74, 197, 'Lambert PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7193, 21, 'Kayla', 'Moore', 'Forward', 74, 234, 'Proctor, Stephenson and Ross');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1690, 20, 'Isaac', 'Edwards', 'Guard', 77, 221, 'Kelly, Gould and Caldwell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3218, 3, 'Jill', 'Ramos', 'Center', 67, 158, 'Dominguez, Freeman and Wiggins');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4972, 18, 'Logan', 'Forbes', 'Forward', 79, 237, 'Stevens and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3727, 2, 'Nicholas', 'Stephenson', 'Center', 66, 168, 'Espinoza-Miller');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2038, 5, 'Melissa', 'Russell', 'Forward', 67, 188, 'Castillo LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6774, 17, 'Madison', 'Schwartz', 'Guard', 85, 234, 'Simpson Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7819, 18, 'Kurt', 'Alvarado', 'Forward', 72, 160, 'Edwards PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2326, 6, 'Brittany', 'Clark', 'Center', 84, 158, 'Campbell Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2895, 9, 'Jeffery', 'Swanson', 'Guard', 69, 215, 'Rodgers, Bowen and Walter');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4457, 2, 'Nathaniel', 'Williams', 'Center', 73, 175, 'Harmon Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4539, 1, 'Curtis', 'Sawyer', 'Forward', 82, 198, 'Rose-Miller');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3401, 23, 'Susan', 'Humphrey', 'Center', 85, 238, 'Choi, Sellers and Owens');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (999, 5, 'Antonio', 'Adams', 'Guard', 71, 170, 'Fisher, Bell and Levine');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8357, 23, 'Michele', 'Christensen', 'Forward', 70, 242, 'Booker Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8233, 22, 'Lisa', 'Davis', 'Forward', 66, 185, 'Holland Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4770, 23, 'Michael', 'Ramirez', 'Forward', 76, 203, 'Fields, Perez and Fields');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2749, 20, 'Ryan', 'Smith', 'Guard', 76, 182, 'Morales, Munoz and Williams');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9201, 22, 'Kaitlyn', 'Hughes', 'Center', 85, 235, 'Wheeler, Salinas and Avery');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7754, 13, 'Angela', 'Odonnell', 'Guard', 69, 207, 'Ellison-Smith');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5285, 18, 'Tamara', 'Blankenship', 'Center', 85, 219, 'Foley, Mitchell and Reyes');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4132, 24, 'Shaun', 'Morgan', 'Guard', 83, 227, 'Parker-Johnson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (804, 8, 'Anita', 'Morris', 'Center', 83, 183, 'Wolfe Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5850, 6, 'Aaron', 'Gomez', 'Forward', 67, 178, 'Kerr Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7448, 8, 'Bobby', 'Jackson', 'Forward', 80, 168, 'Anderson PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9766, 10, 'James', 'Mcdonald', 'Guard', 83, 166, 'Allen and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5769, 11, 'Karen', 'Brown', 'Center', 82, 187, 'Abbott Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3927, 9, 'Michael', 'Mason', 'Guard', 67, 245, 'Diaz, Morris and Russell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4299, 1, 'Timothy', 'Russell', 'Forward', 66, 203, 'Arias Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1208, 4, 'Eric', 'Davis', 'Guard', 66, 179, 'King, Chan and Franklin');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7677, 24, 'Jeffrey', 'Brown', 'Guard', 79, 216, 'Le Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (978, 3, 'Randy', 'Espinoza', 'Forward', 78, 218, 'Gomez-Herrera');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6760, 22, 'Joseph', 'Becker', 'Guard', 65, 187, 'Shaffer, Johnson and Lopez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7251, 3, 'Benjamin', 'Johnson', 'Forward', 78, 201, 'Rojas PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4044, 18, 'Debra', 'Ferguson', 'Guard', 65, 168, 'Stevens, Hamilton and Hall');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1997, 18, 'Amanda', 'Lyons', 'Guard', 66, 208, 'Page-Harvey');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2917, 2, 'Morgan', 'Calderon', 'Guard', 71, 165, 'Barrett Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8425, 20, 'April', 'Heath', 'Forward', 65, 246, 'Pace, Lewis and Ramsey');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5228, 13, 'Jesse', 'Anthony', 'Forward', 76, 216, 'Evans-Palmer');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9688, 16, 'David', 'Howard', 'Center', 73, 196, 'Nunez-Boyer');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (885, 17, 'Alexander', 'Edwards', 'Guard', 67, 157, 'Phillips-Rogers');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4113, 22, 'Sherry', 'Alexander', 'Guard', 71, 249, 'Mcconnell Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1295, 16, 'Matthew', 'Green', 'Center', 69, 180, 'Pena PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1527, 13, 'Hunter', 'Foster', 'Guard', 82, 240, 'Rodriguez LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5708, 11, 'Morgan', 'Le', 'Center', 75, 164, 'Nelson Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9281, 20, 'Jennifer', 'Cook', 'Center', 78, 156, 'Evans-Allen');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6641, 11, 'Kenneth', 'Hancock', 'Guard', 74, 173, 'Leblanc LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4653, 19, 'Hannah', 'Logan', 'Center', 82, 188, 'Young, Sheppard and Brown');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4980, 5, 'Stacey', 'Mccall', 'Forward', 81, 180, 'Romero and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4139, 2, 'Hannah', 'Ball', 'Center', 73, 155, 'Arnold Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (426, 22, 'Timothy', 'Young', 'Forward', 73, 236, 'Brown, Campbell and Brown');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2354, 14, 'Richard', 'Morton', 'Center', 70, 201, 'Jennings, Watkins and Fields');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4077, 20, 'Cody', 'Harrison', 'Forward', 74, 160, 'Rodriguez, Long and Montoya');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4791, 13, 'Tony', 'Mack', 'Center', 74, 181, 'Walker, Garcia and Lewis');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3149, 2, 'Omar', 'Serrano', 'Center', 68, 152, 'Mcbride-Donovan');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7230, 14, 'Ronnie', 'Caldwell', 'Center', 67, 248, 'Clark LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6973, 20, 'Anne', 'Nelson', 'Center', 75, 162, 'Hall-Powell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8735, 15, 'Kristen', 'Shields', 'Guard', 71, 207, 'Brown-James');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1181, 2, 'Marissa', 'Lewis', 'Guard', 84, 181, 'Warren-Mckenzie');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (727, 18, 'Dustin', 'Richardson', 'Forward', 69, 184, 'Cross Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1831, 20, 'Michael', 'Trujillo', 'Center', 67, 174, 'Mosley-Munoz');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3310, 2, 'Scott', 'Martinez', 'Center', 75, 211, 'Schmidt-Hill');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2502, 23, 'Shane', 'Hunter', 'Forward', 83, 200, 'Kelley and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3949, 7, 'John', 'Matthews', 'Forward', 68, 189, 'Jennings, Phillips and Daniels');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2856, 11, 'Alexander', 'Olson', 'Center', 69, 168, 'Krause PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2602, 15, 'Angel', 'Cook', 'Center', 84, 160, 'Lewis-Hoffman');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3472, 14, 'Ashley', 'Smith', 'Center', 69, 161, 'Henderson PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1919, 25, 'Ana', 'Porter', 'Center', 65, 213, 'Schultz-Yoder');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4691, 14, 'Heather', 'Cox', 'Center', 78, 192, 'Spencer and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5105, 3, 'David', 'Rice', 'Forward', 65, 236, 'Sanchez-Mann');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4760, 16, 'Joshua', 'Williams', 'Guard', 73, 183, 'Gutierrez Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1632, 14, 'Whitney', 'Randolph', 'Forward', 80, 234, 'Matthews-Harris');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5807, 5, 'Timothy', 'Santos', 'Center', 79, 226, 'Lee, Steele and Hunter');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9904, 21, 'Angela', 'Brewer', 'Guard', 82, 162, 'Warner and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5872, 8, 'Christopher', 'Bailey', 'Forward', 79, 229, 'Cox-Lara');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1667, 22, 'Richard', 'Jimenez', 'Guard', 68, 247, 'Allen, Hodges and Jackson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5939, 1, 'Joshua', 'Parsons', 'Center', 67, 235, 'Brown-Solomon');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9199, 12, 'Lauren', 'Hall', 'Guard', 75, 242, 'Perry, Reid and Harris');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2497, 12, 'Adam', 'Morgan', 'Guard', 85, 150, 'Parrish Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4046, 13, 'Kellie', 'Wagner', 'Guard', 75, 201, 'Adams-Gonzalez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9397, 13, 'Maria', 'Richardson', 'Guard', 78, 197, 'Williams, Moore and Watkins');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4156, 2, 'Isabella', 'Carter', 'Center', 70, 170, 'Pratt Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (641, 24, 'Carrie', 'Calderon', 'Center', 83, 173, 'Gonzalez Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3063, 1, 'Danielle', 'Hudson', 'Center', 66, 169, 'Stokes Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6390, 23, 'Ernest', 'Rogers', 'Guard', 75, 177, 'Knight PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5006, 7, 'Melissa', 'Johnson', 'Guard', 70, 191, 'Jones-Wiley');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3304, 17, 'Donald', 'Stevens', 'Forward', 77, 200, 'Allen, Gross and Martinez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7701, 17, 'Vanessa', 'Townsend', 'Guard', 75, 155, 'Mccormick, Gates and Johnson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8035, 7, 'Ernest', 'Williams', 'Guard', 67, 150, 'Powers-Keith');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7731, 16, 'Kimberly', 'Francis', 'Forward', 78, 191, 'Jefferson, Kelly and Hampton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3643, 16, 'Stephen', 'Hart', 'Center', 78, 162, 'Gomez Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8667, 2, 'Thomas', 'Johnston', 'Forward', 80, 250, 'Schmidt-Hughes');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7496, 21, 'James', 'Spencer', 'Center', 83, 218, 'Watkins LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5387, 8, 'Tara', 'Rodriguez', 'Guard', 75, 151, 'Velez, Simmons and Davis');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8840, 9, 'Suzanne', 'Martin', 'Forward', 77, 167, 'Holder, Adams and Jimenez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8370, 23, 'Jonathan', 'Bird', 'Guard', 69, 161, 'Fischer-Ramsey');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2600, 3, 'Raymond', 'Elliott', 'Guard', 84, 191, 'Henry, Burgess and Hamilton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (733, 8, 'Hannah', 'Carter', 'Center', 83, 179, 'Zavala-Williams');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8090, 13, 'Matthew', 'Johnston', 'Guard', 83, 178, 'Chang and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3971, 22, 'Kevin', 'Diaz', 'Guard', 67, 163, 'Payne-Ruiz');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1462, 4, 'Jesse', 'Smith', 'Center', 81, 212, 'Davis Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9646, 19, 'David', 'Stevens', 'Center', 72, 187, 'Benton, Irwin and Stokes');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9223, 20, 'Sandy', 'Martinez', 'Center', 67, 250, 'Weber, Crosby and Russo');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (498, 10, 'Paula', 'Wolf', 'Guard', 74, 222, 'Patel PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6566, 7, 'Roger', 'Smith', 'Forward', 84, 170, 'Brown, Griffith and Luna');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4477, 13, 'Jennifer', 'Fisher', 'Center', 69, 248, 'Harrell Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3948, 9, 'Lisa', 'Foster', 'Center', 85, 219, 'Martin LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8414, 6, 'Kevin', 'Lopez', 'Center', 82, 210, 'Willis-Gray');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9095, 1, 'Jennifer', 'Rodriguez', 'Forward', 74, 240, 'Rogers, Ayers and Curry');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9711, 16, 'Trevor', 'Smith', 'Forward', 65, 240, 'Tucker Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6709, 13, 'Peter', 'Nelson', 'Center', 82, 233, 'Acosta Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7194, 22, 'Jaime', 'Smith', 'Center', 75, 154, 'Beck-Griffith');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2815, 7, 'Nancy', 'Carroll', 'Forward', 82, 188, 'Cunningham Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8309, 5, 'Jerry', 'Wilkinson', 'Forward', 80, 231, 'Pierce, White and Cabrera');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2629, 19, 'Raymond', 'Contreras', 'Forward', 84, 211, 'Davis-Hawkins');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5207, 12, 'Amy', 'Mcbride', 'Forward', 71, 218, 'Ramirez, Williams and Cruz');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8677, 2, 'Kathryn', 'Bush', 'Forward', 77, 197, 'Gonzalez-Garcia');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (734, 3, 'Vincent', 'Hood', 'Center', 84, 225, 'Diaz Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8210, 14, 'Jesse', 'Montoya', 'Guard', 78, 201, 'Thomas, Black and Mueller');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8619, 20, 'Daisy', 'Holloway', 'Guard', 79, 217, 'Owens, Gonzales and Johnson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8590, 16, 'Elizabeth', 'Tran', 'Center', 74, 250, 'Hall, Reilly and Gardner');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1556, 11, 'Courtney', 'Weaver', 'Forward', 67, 191, 'Brock Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8797, 14, 'Matthew', 'Good', 'Center', 65, 178, 'Moses, Jacobson and Santana');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9336, 18, 'Jasmine', 'Nash', 'Forward', 75, 189, 'Sutton, Anderson and Cook');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6019, 3, 'Tammy', 'Hill', 'Guard', 70, 231, 'Chase Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5670, 12, 'Ryan', 'Boyd', 'Forward', 75, 157, 'Warren, Webster and Thomas');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9769, 5, 'Matthew', 'Anderson', 'Center', 67, 238, 'Ortiz-Chavez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8273, 18, 'David', 'Arnold', 'Center', 74, 185, 'Fritz-Elliott');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1764, 14, 'Daniel', 'Mayer', 'Forward', 81, 206, 'Garcia Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7642, 21, 'Jason', 'Hardin', 'Forward', 82, 159, 'King, Mathews and Moore');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7835, 24, 'Janet', 'Harrison', 'Forward', 75, 154, 'Gordon, Spencer and Frye');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9730, 12, 'Melissa', 'Jones', 'Forward', 73, 157, 'Silva-Reed');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6232, 13, 'William', 'Klein', 'Guard', 74, 215, 'Newman, Allen and Martinez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6320, 6, 'Todd', 'Cortez', 'Forward', 85, 178, 'Mitchell Group');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (387, 13, 'Joshua', 'Baird', 'Guard', 84, 177, 'Thomas, Mcintosh and Evans');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (284, 18, 'Lee', 'Moreno', 'Guard', 65, 224, 'Mason-Franklin');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4007, 7, 'Catherine', 'Walters', 'Forward', 82, 208, 'Evans LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2253, 2, 'Lisa', 'Wall', 'Guard', 77, 224, 'Cline-Moore');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1897, 25, 'Daniel', 'Jenkins', 'Guard', 65, 156, 'Green, Berg and Davis');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2993, 7, 'Matthew', 'Smith', 'Forward', 68, 247, 'James Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5386, 22, 'Jamie', 'Werner', 'Guard', 80, 175, 'Mason, Brown and Curry');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8153, 17, 'Cindy', 'Gregory', 'Guard', 74, 173, 'Hansen Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8026, 11, 'Christy', 'Evans', 'Forward', 83, 160, 'Coleman-Terry');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2146, 18, 'Joshua', 'Bailey', 'Forward', 81, 220, 'Gordon-Hall');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8439, 17, 'Ann', 'Smith', 'Guard', 71, 211, 'Santiago Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4404, 25, 'Julie', 'Gilmore', 'Guard', 75, 233, 'Snyder, Hall and White');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4442, 18, 'Donna', 'Chandler', 'Guard', 77, 167, 'Cantu, Lopez and Lambert');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (639, 4, 'Susan', 'Herrera', 'Guard', 81, 186, 'Jackson, Cortez and Sampson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7993, 6, 'Larry', 'Jackson', 'Forward', 79, 212, 'Henson-Ross');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5370, 3, 'Tammy', 'Oconnor', 'Forward', 67, 152, 'Green-Garcia');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (171, 20, 'John', 'Fisher', 'Center', 84, 193, 'Brooks-Parker');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5629, 14, 'Angela', 'Santana', 'Center', 82, 226, 'Mercado-Bray');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (687, 2, 'Marie', 'Ball', 'Forward', 76, 225, 'Parker-Patterson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1671, 16, 'Steve', 'Jackson', 'Guard', 79, 170, 'Smith LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3338, 14, 'Mario', 'Stark', 'Center', 72, 223, 'Miller, Dickerson and Williams');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8904, 23, 'Christine', 'Harmon', 'Forward', 79, 217, 'Stewart and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6670, 9, 'Annette', 'Hernandez', 'Guard', 82, 178, 'Chang-Mcfarland');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4137, 25, 'Patricia', 'Long', 'Center', 77, 211, 'Adams, Huffman and Spencer');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5855, 3, 'Alisha', 'Saunders', 'Guard', 69, 206, 'Garcia-Johnson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9702, 16, 'Donna', 'Sanchez', 'Center', 81, 215, 'Fox-Harrison');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3431, 8, 'William', 'Wilson', 'Guard', 84, 171, 'Harris Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1835, 9, 'Charlotte', 'Townsend', 'Center', 74, 180, 'Johnson-Singleton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1497, 5, 'Jack', 'Hebert', 'Forward', 68, 174, 'Lyons and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8162, 19, 'Jason', 'Walton', 'Center', 78, 209, 'Parker-Ryan');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (266, 15, 'Amy', 'Contreras', 'Center', 81, 239, 'Finley LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (582, 2, 'Michael', 'Dunn', 'Forward', 81, 206, 'Wilson PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9549, 6, 'Ryan', 'Cherry', 'Center', 67, 178, 'Waters-Wright');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5238, 6, 'Yvonne', 'Silva', 'Center', 72, 235, 'Mccullough Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9408, 1, 'Alexander', 'Jones', 'Forward', 79, 199, 'Brown, White and Perez');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3812, 18, 'Andre', 'King', 'Forward', 81, 210, 'Delgado, Crawford and Clark');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8728, 6, 'Eric', 'Jefferson', 'Forward', 74, 159, 'Rogers, Obrien and Farmer');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2125, 10, 'Linda', 'Hicks', 'Center', 74, 162, 'Aguilar-Baird');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1565, 6, 'Jeff', 'Turner', 'Center', 77, 179, 'Erickson, Jackson and Evans');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1326, 12, 'Brenda', 'Hutchinson', 'Forward', 77, 227, 'Thomas, Lyons and Bennett');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9640, 22, 'Carlos', 'Fry', 'Forward', 75, 250, 'Salinas, Burns and Campbell');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2596, 15, 'Theresa', 'Woodard', 'Forward', 84, 178, 'Black-Warren');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6314, 11, 'Crystal', 'Wright', 'Center', 82, 242, 'Roth, Gutierrez and Anderson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1190, 14, 'Amanda', 'Murray', 'Center', 78, 157, 'Howard Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8329, 1, 'Kenneth', 'Lewis', 'Forward', 77, 250, 'Orr, Mendoza and Liu');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5409, 8, 'Justin', 'Newman', 'Guard', 85, 186, 'Simmons Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2346, 2, 'Olivia', 'Welch', 'Center', 68, 186, 'Gallegos, Smith and Dixon');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (559, 19, 'Joshua', 'Myers', 'Guard', 77, 157, 'Edwards, Barnes and Brewer');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7434, 17, 'Rachel', 'Cervantes', 'Forward', 66, 241, 'Payne-Wolf');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3307, 17, 'James', 'Fitzgerald', 'Forward', 66, 171, 'Kaiser-Chen');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6847, 11, 'Lindsey', 'Sexton', 'Center', 83, 233, 'Miller, Jackson and Holland');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9042, 8, 'Brian', 'Rodriguez', 'Guard', 77, 241, 'Carter-Spence');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5869, 19, 'James', 'Russell', 'Center', 74, 234, 'Harper-Bush');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (1272, 16, 'Emily', 'Aguilar', 'Forward', 79, 182, 'Richardson and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3826, 16, 'Robert', 'Jones', 'Guard', 68, 211, 'Garcia-Wilson');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4323, 2, 'Charlene', 'Edwards', 'Guard', 80, 197, 'Williams, Walker and Ross');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9371, 16, 'Cynthia', 'Barnett', 'Center', 73, 155, 'Garrett LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4405, 14, 'Angela', 'Cochran', 'Center', 65, 164, 'Kelley, Flores and Martin');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6631, 9, 'Samantha', 'Andrews', 'Guard', 74, 237, 'Martin-Gardner');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7542, 25, 'Lisa', 'Jordan', 'Forward', 80, 243, 'Griffin PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9712, 4, 'Martin', 'Scott', 'Guard', 79, 212, 'Malone-Combs');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2024, 8, 'Ashley', 'Bailey', 'Forward', 77, 194, 'Woods, Hull and Ponce');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9262, 24, 'Diana', 'Martin', 'Guard', 74, 183, 'Jacobs, Burton and Daniels');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5944, 18, 'David', 'Scott', 'Center', 85, 189, 'Allen Ltd');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8548, 20, 'William', 'Williams', 'Guard', 65, 157, 'Taylor LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3087, 11, 'Crystal', 'Sanders', 'Center', 71, 237, 'Hays, Pitts and Ward');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6669, 5, 'Jennifer', 'Vazquez', 'Forward', 70, 169, 'Nelson, Davis and Rivera');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (308, 24, 'Courtney', 'Jones', 'Guard', 67, 189, 'Silva, Lindsey and Ellison');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6210, 9, 'Michelle', 'Johnson', 'Guard', 70, 250, 'Stout-Thomas');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5777, 10, 'Stephen', 'Roberts', 'Center', 67, 232, 'Chase Inc');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (4228, 5, 'Cameron', 'Young', 'Forward', 78, 233, 'Douglas-Barnes');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8085, 7, 'Gerald', 'Lambert', 'Forward', 71, 248, 'Jackson, Diaz and Wright');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2653, 24, 'Andrea', 'Hess', 'Center', 84, 182, 'Thompson LLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (8817, 20, 'Michelle', 'Gonzales', 'Center', 70, 219, 'Caldwell, Washington and Jones');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7791, 9, 'Nicole', 'Gonzalez', 'Guard', 69, 186, 'Russell, Holt and Knapp');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (9037, 2, 'Bryan', 'Reed', 'Center', 80, 226, 'Burnett, Phelps and Melton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (780, 4, 'Robert', 'Fowler', 'Guard', 71, 248, 'Henderson-Norton');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5829, 16, 'Lance', 'Henderson', 'Forward', 67, 165, 'Sanchez PLC');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (5711, 25, 'Karen', 'Alvarez', 'Forward', 71, 185, 'Bell-Avery');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (3526, 22, 'Luis', 'Wright', 'Guard', 84, 187, 'Moss-Edwards');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2915, 6, 'Douglas', 'Cruz', 'Center', 77, 219, 'Stevenson and Sons');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (7806, 4, 'Catherine', 'Brown', 'Forward', 72, 172, 'Davis, Brown and Cochran');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (2227, 13, 'Travis', 'Graves', 'Guard', 70, 196, 'Miranda, Jones and Bradford');
INSERT INTO Player (PlayerID, TeamID, FirstName, LastName, Position, HeightInches, Weight, HighSchool) VALUES (6424, 17, 'Anthony', 'Wyatt', 'Forward', 84, 216, 'Hinton-Smith');
