INSERT INTO Team (TeamID, TeamName, Location) VALUES (1, 'Gibson-Harper', 'East Jennifer');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (2, 'Gordon Ltd', 'South Dianastad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (3, 'Burton-Smith', 'West Virginia');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (4, 'Watkins-Murray', 'Meganport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (5, 'Smith-Wolfe', 'East Mindyshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (6, 'Taylor Ltd', 'Lake Richardfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (7, 'Larsen-Wright', 'Johnberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (8, 'Guerra, Keller and Mccall', 'Marilynmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (9, 'Lee-Terrell', 'Armstrongberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (10, 'Campos, Burton and Gonzalez', 'South Danielleshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (11, 'Ramirez, Bell and Harrell', 'Nathanland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (12, 'Johnson, Richardson and Harrington', 'Kristenmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (13, 'George Group', 'Lake Wendychester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (14, 'West and Sons', 'Lake Sarahtown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (15, 'Zimmerman PLC', 'Romeroborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (16, 'Anderson-Foster', 'Port Judyland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (17, 'Kelly, Mcintyre and Frazier', 'North Chad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (18, 'Poole-Nolan', 'Zacharymouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (19, 'James-Moore', 'Ericaberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (20, 'Schultz Ltd', 'Johnsonton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (21, 'Black Ltd', 'Port Amandabury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (22, 'Aguirre-Jenkins', 'Calderonbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (23, 'Brown-Moreno', 'Bowenland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (24, 'Anderson-Martinez', 'North Ericamouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (25, 'Kelly and Sons', 'Stacyfurt');
