INSERT INTO Team (TeamID, TeamName, Location) VALUES (1, 'Williams, Marquez and Meyers', 'Beardfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (2, 'Elliott, Fuller and Austin', 'Lucastown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (3, 'Powell, Tucker and Mullins', 'West Thomas');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (4, 'Hunt Inc', 'West Brittanyfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (5, 'Mercado, Gonzalez and Watts', 'Lake Sean');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (6, 'Zavala, Allen and Munoz', 'South Sabrina');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (7, 'Nelson, Hendrix and Whitaker', 'North Angela');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (8, 'Calderon Group', 'Jonesfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (9, 'Martinez Ltd', 'Lake Eric');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (10, 'Collins Ltd', 'Johnsonfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (11, 'Lewis, Parker and Rodriguez', 'Beanside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (12, 'Thomas-Galvan', 'Port Valerie');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (13, 'Jackson, Reeves and Holmes', 'Brianview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (14, 'Butler, Vincent and Riddle', 'Hickschester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (15, 'Valdez, Howard and West', 'Kevinside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (16, 'Manning, Baldwin and Williams', 'Jesusmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (17, 'Wilson, Chavez and Kline', 'Richardmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (18, 'Miller-Mitchell', 'Jonesshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (19, 'Hodge Group', 'Langstad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (20, 'Knight-Wright', 'New Tracy');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (21, 'Wright-Townsend', 'West Reginaland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (22, 'Pittman-Greene', 'West Meredith');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (23, 'Ramos, Gonzales and Delacruz', 'Lake Erikaland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (24, 'Williams, Mclaughlin and Rice', 'Port Jennifer');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (25, 'Stuart PLC', 'New Billyside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (26, 'Christensen, Harris and Harris', 'East Abigail');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (27, 'Lara-Wade', 'West Markville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (28, 'Taylor-Clayton', 'East Sherriside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (29, 'Cabrera, Cooper and Mitchell', 'Patriciaborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (30, 'Campbell-Wallace', 'North Lisaburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (31, 'Whitaker, Gonzales and Powell', 'Hughesland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (32, 'Rodriguez, Irwin and Martin', 'Wolfeside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (33, 'Morris-Mccall', 'Floresmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (34, 'Powers, Kaiser and Wilson', 'Sarastad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (35, 'Mason-Davis', 'Castanedaton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (36, 'Berger-Chan', 'East Alvin');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (37, 'Ferrell and Sons', 'Jonesmouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (38, 'Park LLC', 'Franklinbury');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (39, 'Roach-Wells', 'West Amyfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (40, 'Park-Peck', 'Lopezhaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (41, 'Lewis-Roberts', 'Fritztown');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (42, 'Clark PLC', 'East Jayport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (43, 'Brooks-Davis', 'Sonyaside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (44, 'Johnson and Sons', 'North Davidfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (45, 'Garrett, Garcia and Rogers', 'Stevenshaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (46, 'Russell-Freeman', 'Murphyburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (47, 'Williams-Jackson', 'Howestad');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (48, 'Robinson Inc', 'Sloanton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (49, 'Ford, Mullins and Zamora', 'Bellport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (50, 'Lewis, Vaughan and Miller', 'Christinamouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (51, 'Duke Ltd', 'Port Shirleyborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (52, 'Valdez-Garza', 'Lake Kim');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (53, 'Jones LLC', 'Scottfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (54, 'Smith-Foster', 'South Kennethview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (55, 'Wood-Robinson', 'Geraldton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (56, 'Huber-Beltran', 'Lutzview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (57, 'Zhang-Leblanc', 'South Brandon');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (58, 'Cunningham LLC', 'West Chase');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (59, 'Sanchez Inc', 'Martinview');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (60, 'Barnett, Johnson and Stone', 'Port Jesseport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (61, 'Tucker, Mejia and Wilson', 'Catherineberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (62, 'Washington, Watts and Taylor', 'Wardberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (63, 'Mahoney-Long', 'Batesfurt');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (64, 'Parker, Lara and Roberts', 'North Seanfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (65, 'Smith Ltd', 'East Dakotaside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (66, 'Freeman PLC', 'Daisychester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (67, 'Lopez-Lee', 'Port Johnshire');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (68, 'Moore-Phillips', 'Pacemouth');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (69, 'Hines-Wilson', 'Lake David');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (70, 'Carter, Larson and Flores', 'Justinport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (71, 'Duncan LLC', 'North Victoria');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (72, 'Collins, Bradley and Dawson', 'Castroport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (73, 'Parker, Boyd and Armstrong', 'Watkinsborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (74, 'Edwards-Vaughan', 'New Alec');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (75, 'Everett, Calhoun and Foster', 'Joshuahaven');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (76, 'Jones and Sons', 'Stevensfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (77, 'Hamilton, Mcdaniel and Harris', 'Carlborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (78, 'Marshall, Armstrong and Sullivan', 'Andreaborough');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (79, 'Norman PLC', 'Port Michael');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (80, 'Woodard PLC', 'Michaelville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (81, 'Owen and Sons', 'South Stephanie');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (82, 'Mitchell, Brown and Morales', 'Ethanville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (83, 'Taylor PLC', 'North Johnside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (84, 'Davis, Graham and Hernandez', 'Andreaside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (85, 'Miles, Lewis and Mercer', 'Port Grant');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (86, 'Schneider, Meadows and Mccann', 'Savagechester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (87, 'Bray and Sons', 'East Brittanyport');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (88, 'Scott LLC', 'North Jeffreyland');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (89, 'Wallace Ltd', 'Kellyton');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (90, 'Mcmahon-Zuniga', 'Masonchester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (91, 'Barker Group', 'North Jenniferside');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (92, 'Taylor-Mcguire', 'Vasquezburgh');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (93, 'Bailey Group', 'Port Tonyaberg');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (94, 'White, Pitts and Walker', 'Lake Michelle');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (95, 'Paul-Smith', 'East George');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (96, 'Miller PLC', 'West Davidville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (97, 'Smith, Hernandez and Weaver', 'New Richardfort');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (98, 'Castro-Johnson', 'Charlesville');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (99, 'Harrison-Lutz', 'Bethanychester');
INSERT INTO Team (TeamID, TeamName, Location) VALUES (100, 'Richards, Santos and Nelson', 'South Clinton');
